import { IUser } from './types';
// import { IMessage } from '@/types'

// export interface UserGroup {
//   id: string
//   name: string
//   users: IUser[]
// }

export const users: IUser[] = [
  {
    id: '642a119c6e4fc1102cb209b1',
    displayName: 'Louis',
    meta: {
      firstName: 'Louis',
      lastName: 'Lor',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/80540635?v=4',
      avatarUrl: '',
      alt: 'user-1-avatar',
      greeting: 'Ok. See you !',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11b56e4fc1102cb209b2',
    displayName: 'Stanley',
    meta: {
      firstName: 'Stanley',
      lastName: 'Yeung',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11be6e4fc1102cb209b3',
    displayName: 'Keith',
    meta: {
      firstName: 'Keith',
      lastName: 'Wong',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11ca6e4fc1102cb209b4',
    displayName: 'Xavier',
    meta: {
      firstName: 'Xavier',
      lastName: 'Au',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11d66e4fc1102cb209b5',
    displayName: 'Kevin',
    meta: {
      firstName: 'Kevin',
      lastName: 'Tsim',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11e16e4fc1102cb209b6',
    displayName: 'Eric',
    meta: {
      firstName: 'Eric',
      lastName: 'Chan',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11e96e4fc1102cb209b7',
    displayName: 'Alex',
    meta: {
      firstName: 'Alex',
      lastName: 'Cheung',
      avatarUrl:
        'https://c0.klipartz.com/pngpicture/378/42/gratis-png-youtube-colossus-emoji-deadpool-serie-de-peliculas-youtube-thumbnail.png',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11f06e4fc1102cb209b8',
    displayName: 'Silvia',
    meta: {
      firstName: 'Silvia',
      lastName: 'Leung',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a11f76e4fc1102cb209b9',
    displayName: 'William',
    meta: {
      firstName: 'William',
      lastName: 'Chan',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a12076e4fc1102cb209ba',
    displayName: 'Mika',
    meta: {
      firstName: 'Mika',
      lastName: 'Fung',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a120f6e4fc1102cb209bb',
    displayName: 'Terry',
    meta: {
      firstName: 'Terry',
      lastName: 'Chan',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a122a6e4fc1102cb209bc',
    displayName: 'Dominic',
    meta: {
      firstName: 'Dominic',
      lastName: 'Lee',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a123e6e4fc1102cb209bd',
    displayName: 'Raymond',
    meta: {
      firstName: 'Raymond',
      lastName: 'Chu',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
  {
    id: '642a12476e4fc1102cb209be',
    displayName: 'Jan',
    meta: {
      firstName: 'Jan',
      lastName: 'Tong',
      avatarUrl: '',
      // avatarUrl: 'https://avatars.githubusercontent.com/u/41473129?v=4',
      alt: 'user-2-avatar',
      greeting: 'What are you doing',
      lastlyUpdatedAt: new Date(),
      unread: 0,
    },
  },
].sort((user1, user2) => {
  if (user2.displayName < user1.displayName) return 1
  else if(user2.displayName > user1.displayName) return -1
  else return 0;
})

// export const messages: IMessage[] = [
//   {
//     id: 'message-1',
//     position: 'left',
//     type: 'text',
//     title: 'Title 1',
//     text: 'Here is a text type message 1.',
//   },
//   {
//     id: 'message-2',
//     position: 'right',
//     type: 'text',
//     title: 'Title 2',
//     text: 'Here is a text type message 2.',
//   },
//   {
//     id: 'message-3',
//     position: 'left',
//     type: 'text',
//     title: 'Title 3',
//     text: 'Here is a text type message 3.',
//     avatarUrl:
//       'https://www.gstatic.com/images/branding/product/1x/docs_2020q4_48dp.png',
//     titleColor: 'blue',
//     date: new Date('2023-02-01 23:00:00'),
//   },
//   {
//     id: 'message-4',
//     position: 'right',
//     type: 'text',
//     title: 'Title 4',
//     text: 'Here is a text type message 4.',
//     titleColor: 'green',
//     date: new Date('2023-02-01 23:00:00'),
//   },
//   {
//     id: 'message-5',
//     position: 'left',
//     type: 'text',
//     title: 'Title 5',
//     text: 'Here is a text type message 5.',
//   },
//   {
//     id: 'message-6',
//     position: 'right',
//     type: 'text',
//     title: 'Title 6',
//     text: 'Here is a text type message 6.',
//   },
//   {
//     id: 'message-7',
//     position: 'left',
//     type: 'text',
//     title: 'Title 7',
//     text: 'Here is a text type message 7.',
//   },
//   {
//     id: 'message-8',
//     position: 'right',
//     type: 'text',
//     title: 'Title 8',
//     text: 'Here is a text type message 8.',
//   },
//   {
//     id: 'message-9',
//     position: 'left',
//     type: 'text',
//     title: 'Title 9',
//     text: 'Here is a text type message 9.',
//   },
//   {
//     id: 'message-10',
//     position: 'right',
//     type: 'text',
//     title: 'Title 10',
//     text: 'Here is a text type message 10.',
//   },
//   {
//     id: 'message-11',
//     position: 'left',
//     type: 'text',
//     title: 'Title 7',
//     text: 'Here is a text type message 7.',
//   },
//   {
//     id: 'message-12',
//     position: 'right',
//     type: 'text',
//     title: 'Title 8',
//     text: 'Here is a text type message 8.',
//   },
//   {
//     id: 'message-13',
//     position: 'left',
//     type: 'text',
//     title: 'Title 9',
//     text: 'Here is a text type message 9.',
//   },
//   {
//     id: 'message-14',
//     position: 'right',
//     type: 'text',
//     title: 'Title 10',
//     text: 'Here is a text type message 10.',
//   },
// ];

